pangenome_vg: /home/leechuck/Public/software/hapli-nairobi/data/test/pangenome/pangenome.vg
reference: /home/leechuck/Public/software/hapli-nairobi/data/test/reference.fa
output_dir: /home/leechuck/Public/software/hapli-nairobi/data/test/vcf_output
mount_dir: /home/leechuck/Public/software/hapli-nairobi/data/test
sample_names:
- sample_000
- sample_001
- sample_002
threads: 8
vg_docker: quay.io/vgteam/vg:v1.65.0
