reference: /home/leechuck/Public/software/hapli-nairobi/data/test/reference.fa
haplotype_fastas:
- /home/leechuck/Public/software/hapli-nairobi/data/test/variants/sample_000/sample_000_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/test/variants/sample_000/sample_000_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/test/variants/sample_001/sample_001_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/test/variants/sample_001/sample_001_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/test/variants/sample_002/sample_002_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/test/variants/sample_002/sample_002_hap2.fasta
output_dir: /home/leechuck/Public/software/hapli-nairobi/data/test/pangenome
mount_dir: /home/leechuck/Public/software/hapli-nairobi/data/test
threads: 8
cactus_docker: quay.io/comparative-genomics-toolkit/cactus:v2.9.8
vg_docker: quay.io/vgteam/vg:v1.65.0
