reference: /home/leechuck/Public/software/hapli-nairobi/data/large_test/reference.fa
haplotype_fastas:
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_000/sample_000_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_000/sample_000_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_001/sample_001_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_001/sample_001_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_002/sample_002_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_002/sample_002_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_003/sample_003_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_003/sample_003_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_004/sample_004_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_004/sample_004_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_005/sample_005_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_005/sample_005_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_006/sample_006_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_006/sample_006_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_007/sample_007_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_007/sample_007_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_008/sample_008_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_008/sample_008_hap2.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_009/sample_009_hap1.fasta
- /home/leechuck/Public/software/hapli-nairobi/data/large_test/samples/sample_009/sample_009_hap2.fasta
output_dir: /home/leechuck/Public/software/hapli-nairobi/data/large_test/pangenome
mount_dir: /home/leechuck/Public/software/hapli-nairobi/data/large_test
threads: 8
cactus_docker: quay.io/comparative-genomics-toolkit/cactus:v2.8.4
vg_docker: quay.io/vgteam/vg:v1.65.0
