# General settings
threads: 8

# Reference genome generation settings
reference_genome_dir: "results/reference"
num_chromosomes: 3
base_length: 1000000
decay: 0.9
gc_content: 0.41
seed: 42

# Variant generation settings
variant_data_dir: "results/variant_data"
num_samples: 2
variants_per_haplotype: 5

# VCF generation settings
# Reference path name in the graph (should match the ID in reference.fasta)
reference_name: "reference"
